#ifndef CONFIG_H
#define CONFIG_H

//CREDENCIALES DE RED Y TELEGRAM
#define WIFI_SSID_DEFECTO "UTNFRC"
#define WIFI_CLAVE_DEFECTO ""
#define PREFERENCES_NS "wifi_creds"

#define TOKEN_BOT "8444785999:AAFXDQE1KP1wdjh0JGw4b-xsq0FxqFU2Nkg"
#define CHAT_ID "-1003100355289"
#define INTERVALO_BOT_MS 1000 // INTERVALO ENTRE LECTURA DE MSJS- IMPORTANTE

// DEFINICION DE PINES POR DEFECTO
#define PIN_GAS 32
#define PIN_TEMP 4
#define PIN_ZUMBADOR 12

#define TIPO_DHT DHT11

#define LIMITE_TEMP_DEFECTO 35

//BUFFER DEL PUERTO SERIE
#define TAM 10
#define MAX_LEN 50

#endif